import phonenumbers
import time
import datetime
y = datetime.datetime.now()
z = input("Enter reciever id : ")
print(" ")
x = input("type your message : ")
print(" ")
print("Loading....")
print(" ")
time.sleep(5)
print("Recieving data packages")
print(" ")
time.sleep(2)
print("Sending data packages")
print(" ")
time.sleep(1)
print(3)
time.sleep(1)
print(" ")
print(2)
time.sleep(1)
print(" ")
print(1)
print(" ")
print("The message '"+str(x)+"' has sent to the user "+str(z)+" now on "+str(y))